### ISSUE TITLE
windows pc not working

### ISSUE THREAD

**Issue by serdartaylan** [msamgan/vscode-larapint#18]
I couldn't run the plugin on my windows10 computer.
I am using the latest version vscode and plugin.

I get a pint upload warning when I want to save the file.
(whereas pint is installed and I can run it with terminal)

"Pint binary not found. Do you want to install it?"
when i click "yes"
"Something went wrong while running Laravel Pint."
and
"Starting download..."
It gives a warning but doesn't offer a solution.

file save after
![image](https://user-images.githubusercontent.com/1150010/182036013-e552ed78-c889-488b-9fed-3156cafb0eba.png)

yes click
![image](https://user-images.githubusercontent.com/1150010/182036036-ada1f5a9-179a-4254-9c27-a0ac6905c15e.png)

terminal screen
![image](https://user-images.githubusercontent.com/1150010/182035989-182e0556-504a-4cf7-9234-f4f36cb2c42b.png)

**Comment by serdartaylan** [comment]
command prompt 
![image](https://user-images.githubusercontent.com/1150010/182038921-0e4226b2-6c17-469e-8dab-cb09ed03f3fc.png)

Windows PowerShell
![image](https://user-images.githubusercontent.com/1150010/182038995-f6700726-ab99-4af8-842a-373d6e36349c.png)

git-bash
![image](https://user-images.githubusercontent.com/1150010/182039065-40bc7e64-9844-4e71-ad5c-11ac89a37610.png)

**Comment by msamgan** [comment]
thanks for pointing out, Ill look into this..
can you also give me your php version please.

**Comment by serdartaylan** [comment]
composer.json
```
"require": {
        "php": ">=8.0",
}
```

**Comment by serdartaylan** [comment]
I have temporarily created a solution with another plugin. Maybe the method I used can guide you.

https://marketplace.visualstudio.com/items?itemName=pucelle.run-on-save

Thanks to this plugin, I can run commands after saving the file.

my config
`    "runOnSave.commands": [
        {
            "match": ".*\\.php$",
            "runIn": "backend",
            "async":true,
            "command": "php vendor/bin/pint ${fileRelative}",
            "runningStatusMessage": "${fileBasename} pint running",
            "finishStatusMessage": "${fileBasename} pint completed"
        },
    ],`

**Comment by msamgan** [comment]
i tries to recreate this issue, wasn't able to recreate.
all works as expected.
i am closing this issue for now.
but ill keep an eye if this can be recreated..

**Comment by msamgan** [comment]
thanks for reference of the issue for the permission.
i tried to recreate it on windows, was not able to.
i will close this issue for now bit will keep an eye on the same if it can be recreated.

**Comment by msamgan** [comment]
@serdartaylan i deleted you comment regarding  https://marketplace.visualstudio.com/items?itemName=pucelle.run-on-save by mistake, please feel free to recomment.

**Comment by msamgan** [comment]
https://github.com/msamgan/vscode-larapint/compare/v0.1.1...v0.1.2

resolved here.

**Comment by serdartaylan** [comment]
did you test this?

**Comment by faperreault** [comment]
@msamgan Had the same issue. I debugged your extension and saw the following error 

```
Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
```

Realised it might be a PATH problem for some people. Anyway my path cmd was fine. I change the line 12 in `/utils/methods.js` to a hardcoded path to my project and it works fine now. 

![image](https://user-images.githubusercontent.com/9636082/184186984-f40ad3e0-7b7a-415b-9325-77cabd0b3b89.png)

This is the issue. Basically compare to my hardcoded one it had a `/` at the beginning which caused it to be an invalid path. Also it take the first folder from your workspace which is not always a php project with composer so maybe that line should change?

**Comment by msamgan** [comment]
@phadaphunk thanks for pointing out.
it will be highly appreciated if you can create a PR with your proposed solution to the problem and we can take it from there.
