### ISSUE TITLE
Extension is configured as formatter but it cannot format php files

### ISSUE THREAD

**Issue by gsabater** [msamgan/vscode-larapint#26]
Hello,

I get this error when i try to format a selection of code with vscode and this extension.

I do have the extension configured in settings.json, with the following snippet. No other settings collide with this in global config.
```
  "[php]": {
    "editor.tabSize": 4,
    "editor.formatOnSave": false,
    "editor.defaultFormatter": "open-southeners.laravel-pint",
  },
```

I also have a pint.json in the root of the project.
The error shown is the following, and only happens when i select text, and then right click and format selection

![image](https://github.com/3rd-planet/vscode-larapint/assets/4948172/5cdde11c-f507-475c-b7ad-88abc1d280f0)

**Comment by msamgan** [comment]
this is not my extension brother.
this is another one from open southerners. wrong repo.

**Comment by gsabater** [comment]
Lol, sorry dude, i dont know how could this happen.
sry
